# Generated by Django 6.0 on 2026-01-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_course_code_and_more'),
        ('programs', '0003_alter_program_abbrev_alter_program_comment_and_more'),
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('task', models.CharField(db_index=True, max_length=255, verbose_name='Task type')),
                ('groupno', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='GroupNumber')),
                ('submitdate', models.DateField(null=True, verbose_name='Submission date')),
                ('students', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='courses.course', verbose_name='Course')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='programs.program', verbose_name='Program')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='stationery.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
