# Generated by Django 6.0 on 2026-01-26 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_options_alter_course_code_and_more'),
        ('programs', '0003_alter_program_abbrev_alter_program_comment_and_more'),
        ('stationery', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='streams',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='groupno',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='page',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='programs.program'),
        ),
        migrations.AlterField(
            model_name='page',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='stationery.question'),
        ),
        migrations.AlterField(
            model_name='page',
            name='submitdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='task',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
