# Generated by Django 6.0 on 2026-01-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_page_streams_alter_page_course_alter_page_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='submitdate',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
