# Generated by Django 6.0 on 2026-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0004_alter_page_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='streams',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
