# Generated by Django 6.0 on 2026-01-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0005_alter_page_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='question',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
