# Generated by Django 6.0 on 2026-01-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0006_alter_page_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='students',
            field=models.JSONField(default=None, null=True),
        ),
    ]
