# Generated by Django 6.0 on 2026-01-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0007_alter_page_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='students',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
