# Generated by Django 6.0 on 2026-01-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0010_alter_page_streams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='streams',
        ),
    ]
