# Generated by Django 6.0 on 2026-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0011_remove_page_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='streams',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
