# Generated by Django 6.0 on 2026-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0013_alter_page_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='table',
            field=models.BooleanField(default=True),
        ),
    ]
