# Generated by Django 6.0 on 2026-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0014_page_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
