# Generated by Django 6.0 on 2026-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
