# Generated by Django 6.0 on 2026-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The full name of the facilitator', max_length=255, verbose_name='Facilitator Name')),
                ('comment', models.TextField(blank=True, help_text='Any additional notes about the facilitator', null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this facilitator was created', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Facilitator',
                'verbose_name_plural': 'Facilitators',
                'ordering': ['name'],
            },
        ),
    ]
