# Generated by Django 6.0 on 2026-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0002_alter_facilitator_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Facilitator Name'),
        ),
    ]
