# Generated by Django 6.0 on 2026-01-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_alter_program_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(help_text='The full name of the student', max_length=255, verbose_name='Full Name')),
                ('regnumber', models.CharField(help_text='A unique registration number for the student', max_length=50, unique=True, verbose_name='Registration Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this student record was created', verbose_name='Created At')),
                ('program', models.ForeignKey(blank=True, default=None, help_text='The program in which the student is enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['fullname'],
            },
        ),
    ]
