# Generated by Django 6.0 on 2026-01-25 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_abbrev_alter_program_comment_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='programs.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='regnumber',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Registration Number'),
        ),
    ]
