# Generated by Django 6.0 on 2026-01-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilitators', '0002_alter_facilitator_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The full name of the course', max_length=255, verbose_name='Course Name')),
                ('code', models.CharField(help_text='A short, unique code for the course', max_length=50, unique=True, verbose_name='Code')),
                ('comment', models.TextField(blank=True, default=None, help_text='Any additional notes about the course', null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this course was created', verbose_name='Created At')),
                ('facilitator', models.ForeignKey(blank=True, default=None, help_text='The facilitator assigned to this course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilitators.facilitator', verbose_name='Facilitator')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
    ]
