# Generated by Django 6.0 on 2026-01-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comment',
        ),
    ]
