# Generated by Django 6.0 on 2025-12-20 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Required. 32 characters or fewer. Only alphabets (a-zA-Z).', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed.', regex='^[a-zA-Z]+$')], verbose_name='Username')),
                ('fullname', models.CharField(help_text="The user's full name", max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, default=None, help_text="User's phone number in international format", max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?1?\\d{9,13}$')], verbose_name='Phone Number')),
                ('last_login', models.DateTimeField(blank=True, default=None, help_text="Date and time of the user's last login", null=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active (not blocked).', verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user has admin privileges', verbose_name='Admin Status')),
                ('deleted', models.BooleanField(default=False, help_text='Designates whether this user has been deleted', verbose_name='Deleted')),
                ('comment', models.TextField(blank=True, default=None, help_text='Additional notes about the user', null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the user was last updated', verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users', to='auth.group', verbose_name='Groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', to='auth.permission', verbose_name='User Permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'customuser',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='customuser_usernam_2f899c_idx'), models.Index(fields=['fullname'], name='customuser_fullnam_17503d_idx'), models.Index(fields=['created_at'], name='customuser_created_bfaaec_idx'), models.Index(fields=['is_active', 'deleted'], name='customuser_is_acti_51c708_idx')],
            },
        ),
    ]
