# Generated by Django 6.0 on 2026-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='comment',
            field=models.TextField(blank=True, default=None, help_text='Any additional notes about the program', null=True, verbose_name='Comments'),
        ),
    ]
