# Generated by Django 6.0 on 2026-01-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='abbrev',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='program',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Program Name'),
        ),
    ]
